title: 技术分享
tagline: 技术分享
description: 最近碰到的问题
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://rabbit77.github.io # the base hostname & protocol for your site

author:
  name: gongjianmei
  email: rabbit7_77@163.com
  github: rabbit77
  twitter: rabbit77
  weibo: feiniaohuaxi
start_year: 2017

permalink: /:year/:month/:day/:title
timezone: Asia/BeiJing

tags_path: /tags.html
feed_path: /feed.xml

markdown: kramdown
# highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

service:
  comment: disqus
  disqus:
    short_name: rabbit77coding
  duoshuo:
    short_name: rabbit77coding


exclude: [README.md, CNAME]
